meta_product_name: "One-Cliq"
meta_title: "One-Cliq Connects together!"
meta_description: "Connecting parents to school."
meta_image: "card.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
